OPTS+=" --enable-locking       \
        --with-pthread         \
        --with-dpms-ext        \
        --with-xshm-ext        \
        --without-gle          \
        --without-setuid-hacks \
        --without-kerberos"

default_build
